### ISSUE TITLE
NUX buttons are truncated on smaller devices

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPressAuthenticator-iOS#155]
I just launched the app on the iPhone SE simulator, and noticed that the "continue with..." buttons in the NUX are truncated on smaller devices.

Per pbArwn-5X-p2, scale the button text to fit the width instead of truncating.

<img src="https://user-images.githubusercontent.com/4780/68702388-a4f9ab80-0580-11ea-897d-f156aba652d9.png" width="300" />

I guess we'll need to either wrap the text or shrink it when this happens.

**Comment by mindgraffiti** [comment]
Related host app issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13466

**Comment by ScoutHarris** [comment]
Reopening as this is no longer fixed with https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/213. For reference, the change that reverted the fix (in order to fix something else) was https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/216.

**Comment by mindgraffiti** [comment]
Also related: NUXButton doesn't shrink back down to the correct size when Dynamic Text is applied (make it a much larger size), then re-applied (set it back to normal).
