### ISSUE TITLE
Remove whitespace from translated Continue with Google string

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#220]
Ref. p1585064399263400-slack-C02Q9GACF

Per this comment: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/213/files#r397251803 see if it's possible to isolate the whitespace away from the localized string, as it causes issues for our translators.

Target WPiOS 14.5 build.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/223.

**Comment by mindgraffiti** [comment]
Thanks @ScoutHarris 🙇‍♀ 

 I forgot these don't automatically close
