### ISSUE TITLE
Update the GoogleSignIn library when a version without UIWebView will be released

### ISSUE THREAD

**Issue by pmusolino** [wordpress-mobile/WordPressAuthenticator-iOS#236]
On Woo app, we continue to receive the message from Apple about the deprecated API usage for `UIWebView`.

It looks like `GoogleSignIn` does use UIWebView in their binaries:
```
-> % strings /Users/aaron/src/woocommerce-ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn  | grep -i uiwebview
l_OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
l_OBJC_PROTOCOL_$_UIWebViewDelegate
l_OBJC_LABEL_PROTOCOL_$_UIWebViewDelegate
l_OBJC_PROTOCOL_$_UIWebViewDelegate
UIWebViewDelegate
B40@0:8@"UIWebView"16@"NSURLRequest"24q32
v24@0:8@"UIWebView"16
v32@0:8@"UIWebView"16@"NSError"24
@"UIWebView"
T@"UIWebView",W,N,V_webView
... 
```

In their [changelog](https://developers.google.com/identity/sign-in/ios/release) I don’t see any reference to `UIWebView`, so I believe that even updating to the latest version available (5.0.2), we will continue to see the warning. 
**The library will need to be updated when a version that does not use `UIWebView` will be available.**

**Comment by bummytime** [comment]
> On Woo app, we continue to receive the message from Apple about the deprecated API usage for UIWebView.

WPiOS is getting this same warning from Apple on every release. 

Let's try and get this done in the near term. We need to determine if migrating from 4.4.0 to 5.0.2 holds any surprises for us.

@designsimply, could we bump this to the top of the groundskeeping queue?

/cc @frosty

**Comment by frosty** [comment]
> In their changelog I don’t see any reference to UIWebView, so I believe that even updating to the latest version available (5.0.2), we will continue to see the warning.
I tested pulling in 5.0.2 (without updating our app), and I don't see any references to UIWebView in the binary, so we might actually be okay if we update.

**Comment by bummytime** [comment]
> so we might actually be okay if we update.

@frosty if you and @pmusolino are good with this lib update, perhaps we can open a PR and give it a good round of testing on Woo/WPiOS?

**Comment by pmusolino** [comment]
@bummytime sure. I can take care of it 😃👍
