### ISSUE TITLE
Site address option disappears after sending magic link

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPressAuthenticator-iOS#251]
### Expected

I should always be able to go back to a previous step in the flow and choose a different option.

### Actual 

If I choose the email/magic link flow, and go back after sending the magic link, the site address option disappears from the email screen. I have to go all the way back to the prologue screen and start over.

This happens in multiple apps using WordPressAuthenticator (WordPress, WooCommerce).

### Steps to reproduce

These are steps to repro in WordPress:

1. Select "Log In."
2. Select "Continue with WordPress.com."
3. Enter your WordPress.com account email address and select "Next."
4. Select "Send Link."
5. Tap back twice to return to the email screen, and notice that the option to log in with site address is gone.

Initial email screen|Email screen after going back
-|-
<img src="https://user-images.githubusercontent.com/8658164/79986808-8808c300-84a4-11ea-808e-7449c6b68f02.PNG" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/79986880-9ce55680-84a4-11ea-9beb-a9f190da9341.PNG" width="300px">

**Comment by mindgraffiti** [comment]
This one will be fixed once the new unified login & email view controller is built.

**Comment by mindgraffiti** [comment]
The old UI remains, but all apps are / will be taking steps to update to the new UI. The new UI has moved the "log in by Site Address" flow out of the "login by email" view, making this bug no longer relevant. 

**New UI implemented in WPiOS 15.7**
<a href="https://user-images.githubusercontent.com/1062444/92520889-efb87400-f1e1-11ea-88d4-422402130c00.png"><img src="https://user-images.githubusercontent.com/1062444/92520889-efb87400-f1e1-11ea-88d4-422402130c00.png" width="350" /></a>

https://github.com/wordpress-mobile/WordPress-iOS/pull/14771
