### ISSUE TITLE
WooCommerce authentication URL access	

### ISSUE THREAD

**Issue by olvs** [wordpress-mobile/WordPressAuthenticator-iOS#3]
Hello,

I facing an issue that I don't understand the meaning : Some hosts have unnecessarily intrusive security checks in place that prevent WooCommerce API authentication from working (mod_security rule #1234234). If this check fails, you will not be able authorize Printful app = FAIL

![capture d ecran 2018-06-03 a 17 14 21](https://user-images.githubusercontent.com/19269602/40888287-50f53ee8-6755-11e8-9dc7-713af0592429.png)

Any Ideas ? Thanks

**Comment by mindgraffiti** [comment]
Hey @olvs. I'm closing this issue because doesn't sound related to the WordPressAuthenticator-iOS framework. 

>If this check fails, you will not be able authorize Printful app = FAIL

You might contact the Printful team's support to see if they can help you configure your extension.
