### ISSUE TITLE
SIWA: Apple logo background renders weird in press down state

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressAuthenticator-iOS#392]
The Apple logo in the "Continue with Apple" logo looks weird during the press-down state of the button. I have dark mode enabled in the simulator when recording this (with animations slowed):

![2020-08-20_13-08-53 (1)](https://user-images.githubusercontent.com/373903/90809193-b7aac900-e2e6-11ea-8f73-3c381dbe9175.gif)

**Comment by jaclync** [comment]
Maybe we can try removing the black/white background for the assets ([apple-white.pdf](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/0b3af0ff19b60e304e02cc82b058d4a57b18e01a/WordPressAuthenticator/Resources/Assets.xcassets/apple-white.imageset/apple-white.pdf) and [apple-black.pdf](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/0b3af0ff19b60e304e02cc82b058d4a57b18e01a/WordPressAuthenticator/Resources/Assets.xcassets/apple-black.imageset/apple-black.pdf)) to fix this?
