### ISSUE TITLE
ULS Tracking: Password challenge step

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPressAuthenticator-iOS#405]
Ref: pbArwn-AP-p2#comment-1487

To keep parity between Android & iOS, let's change the Tracks step `username_password` to `password_challenge`.

Implement `password_challenge` step for when loging in with SIWA / Google, using a WP account that has a password set, and is disconnected from SIWA / Google.

**Comment by mindgraffiti** [comment]
Closed via #407.
