### ISSUE TITLE
Google Authenticator 2FA codes with leading zeros are copied without the leading zero

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPressAuthenticator-iOS#557]
This causes the continue button to not be enabled as a result:

![step1](https://user-images.githubusercontent.com/1595739/103959087-9581de00-5103-11eb-9d98-aee10f74dccc.png)

![step2](https://user-images.githubusercontent.com/1595739/103959096-9a469200-5103-11eb-94a9-6e5a69ad9608.png)

I think it is because of this Int cast: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/108a03cf8b2b1ae0cca34538bb5c1abdebc6845a/WordPressAuthenticator/Unified%20Auth/View%20Related/2FA/TwoFAViewController.swift#L324

**Comment by ctarda** [comment]
Wow, nice catch! Thanks a lot for logging this @allendav
