### ISSUE TITLE
Update GoogleSignIn dependency to 6.0

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPressAuthenticator-iOS#609]
Now that GoogleSignIn has been [updated with M1 support](https://developers.google.com/identity/sign-in/ios/release), let's update the version used by the authenticator pod to 6.0.x.
Alternatively, if there is adequate support via https://developer.apple.com/documentation/authenticationservices we could use that instead, but may need more investigation.

**Comment by jkmassel** [comment]
I'd personally prefer using the iOS native approach given [the number of libraries](https://github.com/google/GoogleSignIn-iOS/blob/8b930883887987189dfa2a991e4bba90620f018f/GoogleSignIn.podspec#L32-L34) that are pulled in as part of this 😅

There is _some_ [work-in-progress on this](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/tree/remove/google-authenticator-library) that myself and @ctarda looked at, if that's useful at all?

**Comment by aerych** [comment]
Tough to say how close the WIP got just by looking at the branch.  Did y'all have a sense for how far a long it was? @ctarda, @jkmassel
