### ISSUE TITLE
Passkeys consistently return app identifier error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPressAuthenticator-iOS#825]
Passkeys seems to be broken due to an issue with the app identifiers. I see the same issue in both Woo and WordPress apps.

In Woo, I get the error message "Whoops, something went wrong. Please try again!" and this error in the logs:

```
Error signing challenge: The operation couldn't be completed. Application with identifier PZYM8XX95Q.com.automattic.woocommerce is not associated with domain wordpress.com
```

I get the same error in WordPress but with the WordPress app identifier.

I'm not sure what's going wrong, because I see those app identifiers in the [WordPress.com apple-app-site-association file](https://wordpress.com/.well-known/apple-app-site-association).

**Comment by Ecarrion** [comment]
Closing as it appears to be a temporary glitch server-side.
